[package]
name = "excel-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.21.2"
csv = "1.2.2"

[dev-dependencies]
serde = { version = "1.0.164", features = ["derive"] }
